/**
 * 국가 코드 → 국가명 매핑 유틸
 * 
 * geoip-lite는 국가 코드만 제공하므로, 국가명 매핑이 필요합니다.
 * ISO 3166-1 alpha-2 코드를 국가명으로 변환합니다.
 */

const COUNTRY_NAMES = {
    'KR': 'Korea, Republic of',
    'US': 'United States',
    'JP': 'Japan',
    'CN': 'China',
    'GB': 'United Kingdom',
    'DE': 'Germany',
    'FR': 'France',
    'IT': 'Italy',
    'ES': 'Spain',
    'CA': 'Canada',
    'AU': 'Australia',
    'BR': 'Brazil',
    'IN': 'India',
    'RU': 'Russian Federation',
    'MX': 'Mexico',
    'ID': 'Indonesia',
    'NL': 'Netherlands',
    'SE': 'Sweden',
    'NO': 'Norway',
    'DK': 'Denmark',
    'FI': 'Finland',
    'PL': 'Poland',
    'TR': 'Turkey',
    'TH': 'Thailand',
    'VN': 'Vietnam',
    'PH': 'Philippines',
    'MY': 'Malaysia',
    'SG': 'Singapore',
    'HK': 'Hong Kong',
    'TW': 'Taiwan',
    'NZ': 'New Zealand',
    'CH': 'Switzerland',
    'AT': 'Austria',
    'BE': 'Belgium',
    'PT': 'Portugal',
    'GR': 'Greece',
    'IE': 'Ireland',
    'CZ': 'Czech Republic',
    'HU': 'Hungary',
    'RO': 'Romania',
    'BG': 'Bulgaria',
    'HR': 'Croatia',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'LT': 'Lithuania',
    'LV': 'Latvia',
    'EE': 'Estonia',
    'LU': 'Luxembourg',
    'IS': 'Iceland',
    'MT': 'Malta',
    'CY': 'Cyprus',
    'AR': 'Argentina',
    'CL': 'Chile',
    'CO': 'Colombia',
    'PE': 'Peru',
    'VE': 'Venezuela',
    'ZA': 'South Africa',
    'EG': 'Egypt',
    'AE': 'United Arab Emirates',
    'SA': 'Saudi Arabia',
    'IL': 'Israel',
    'PK': 'Pakistan',
    'BD': 'Bangladesh',
    'MM': 'Myanmar',
    'KH': 'Cambodia',
    'LA': 'Laos',
    'BN': 'Brunei',
    'MO': 'Macao',
    'MN': 'Mongolia',
    'KZ': 'Kazakhstan',
    'UZ': 'Uzbekistan',
    'GE': 'Georgia',
    'AM': 'Armenia',
    'AZ': 'Azerbaijan',
    'BY': 'Belarus',
    'UA': 'Ukraine',
    'MD': 'Moldova',
    'RS': 'Serbia',
    'BA': 'Bosnia and Herzegovina',
    'MK': 'North Macedonia',
    'AL': 'Albania',
    'ME': 'Montenegro',
    'XK': 'Kosovo',
    'DZ': 'Algeria',
    'MA': 'Morocco',
    'TN': 'Tunisia',
    'LY': 'Libya',
    'SD': 'Sudan',
    'ET': 'Ethiopia',
    'KE': 'Kenya',
    'TZ': 'Tanzania',
    'UG': 'Uganda',
    'GH': 'Ghana',
    'NG': 'Nigeria',
    'AO': 'Angola',
    'MZ': 'Mozambique',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
    'BW': 'Botswana',
    'NA': 'Namibia',
    'MU': 'Mauritius',
    'RE': 'Réunion',
    'SC': 'Seychelles',
    'MV': 'Maldives',
    'LK': 'Sri Lanka',
    'NP': 'Nepal',
    'BT': 'Bhutan',
    'AF': 'Afghanistan',
    'IQ': 'Iraq',
    'IR': 'Iran',
    'JO': 'Jordan',
    'LB': 'Lebanon',
    'SY': 'Syria',
    'YE': 'Yemen',
    'OM': 'Oman',
    'QA': 'Qatar',
    'KW': 'Kuwait',
    'BH': 'Bahrain',
    'YE': 'Yemen',
    'IQ': 'Iraq',
    'IR': 'Iran',
    'JO': 'Jordan',
    'LB': 'Lebanon',
    'SY': 'Syria',
    'YE': 'Yemen',
    'OM': 'Oman',
    'QA': 'Qatar',
    'KW': 'Kuwait',
    'BH': 'Bahrain',
};

/**
 * 국가 코드를 국가명으로 변환
 * @param {string|null} countryCode - ISO 3166-1 alpha-2 국가 코드 (예: 'KR', 'US')
 * @returns {string|null} 국가명 (예: 'Korea, Republic of', 'United States') 또는 null
 */
function getCountryName(countryCode) {
    if (!countryCode || typeof countryCode !== 'string') {
        return null;
    }
    
    const code = countryCode.toUpperCase();
    return COUNTRY_NAMES[code] || null;
}

module.exports = { getCountryName };

